version: "2.1"

services:
  db:
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: singularity
    volumes:
      - singularity_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  singularity_api:
    image: datapreservationprogram/singularity:latest
    command: run api
    ports:
      - 9090:9090
    environment:
      DATABASE_CONNECTION_STRING: postgres://postgres:postgres@db:5432/singularity
    depends_on:
      db:
        condition: service_healthy

  singularity_dataset_worker:
    image: datapreservationprogram/singularity:latest
    command: run dataset-worker
    environment:
      DATABASE_CONNECTION_STRING: postgres://postgres:postgres@db:5432/singularity
    depends_on:
      db:
        condition: service_healthy
volumes:
  singularity_db:
