version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: singularity
    ports:
      - 5432:5432

  singularity_api:
    image: datapreservationprogram/singularity:latest
    command: run api
    ports:
      - 9090:9090
    environment:
      DATABASE_CONNECTION_STRING: postgres://postgres:postgres@db:5432/singularity
    depends_on:
      - db

  singularity_dataset_worker:
    image: datapreservationprogram/singularity:latest
    command: run dataset-worker
    environment:
      DATABASE_CONNECTION_STRING: postgres://postgres:postgres@db:5432/singularity
    depends_on:
      - db
